run:
  timeout: 10m

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - megacheck
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

linters-settings:
  funlen:
    lines: 150
    statements: 150
  lll:
    line-length: 200
  govet:
    check-shadowing: false
  dupl:
    threshold: 1000
  stylecheck:
    checks: ["all", "-ST1000"]
  gocyclo:
    min-complexity: 20
issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - lll
        - funlen
        - dupl